name: CI Pipeline

on: [push]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v2

            - name: Set Up Python
              uses: actions/setup-python@v2
              with:
                python-version: '3.9'
            
            - name: Install Dependencies
              run: pip install pylint
            
            - name: Run Pylint
              run: pylint calculator.py
            
            - name: Run Tests
              run: python -m unittest discover
            
            - name: Build Docker Image
              run: docker build -t rashi/calculator-app .
            
            - name: Log in to Docker Hub
              run: echo "$({ secrets.DOCKER_HUB_PASSWORD })" | docker login -u "rashi" --password-stdin

            - name: Push Docker Image
              run: docker push rashi/calculator-app
